[tool.poetry]
name = "strela"
version = "0.1.0"
description = ""
authors = ["ymyke <michael.naef@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.7,<3.10"
pandas = ">=1.4.3"
yagmail = ">=0.15.280"
# ^ FIXME Use productive package when ready
tessa = {git = "https://github.com/ymyke/tessa.git", rev = "add-symbols"}
python-slugify = ">=5.0.0"

[tool.poetry.dev-dependencies]
pytest = "*"
black = "*"
pylint = "*"
ipykernel = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
